# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1280f48b03373ee87d4ece27c0c88912cd4ae702e6dd14d96773096247aeb6a7546a2fa9134177270d7d3a784cfbafcb9c068444fa8edd9888646885a20f439c

test:
  secret_key_base: 88135ee03abdfe4a86df8b92cae8a87a36e18a91461962da3928aa2707e22a06dc7185a4d8da333f444e389e4508a0eb897b85c96b4e7463a26022055d07bcfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
